login: &login
  adapter: mysql
  host: localhost
  username: carlbtan_carlb
  password: melorbode

development:
  database: find_a_store_development
  <<: *login

test:
  database: find_a_store_test
  <<: *login

production:
  database: find_a_store_production
  <<: *login

